// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef CONNECTION_STRING_KEYS_H
#define CONNECTION_STRING_KEYS_H

#include "rds_strings.h"

/* Generic */
#define VALUE_BOOL_FALSE TEXT("0")
#define VALUE_BOOL_TRUE TEXT("1")

#define KEY_DATABASE TEXT("DATABASE")
#define KEY_SERVER TEXT("SERVER")
#define KEY_PORT TEXT("PORT")

#define KEY_BASE_DRIVER TEXT("BASE_DRIVER")
#define KEY_DRIVER TEXT("DRIVER")
#define KEY_BASE_DSN TEXT("BASE_DSN")
#define KEY_DSN TEXT("DSN")

#define KEY_SAVEFILE TEXT("SAVEFILE")
#define KEY_FILEDSN TEXT("FILEDSN")
#define KEY_DESC TEXT("DESCRIPTION")
#define KEY_BASE_CONN TEXT("BASE_CONN")

#define ODBC TEXT("ODBC")
#define ODBC_DATA_SOURCES TEXT("ODBC Data Sources")

/* Auth */
#define KEY_AUTH_TYPE TEXT("RDS_AUTH_TYPE")
#define KEY_DB_USERNAME TEXT("UID")
#define KEY_DB_PASSWORD TEXT("PWD")

/* Auth Types */
#define VALUE_AUTH_DATABASE TEXT("DATABASE")
#define VALUE_AUTH_IAM TEXT("IAM")
#define VALUE_AUTH_SECRETS TEXT("SECRETS_MANAGER")
#define VALUE_AUTH_ADFS TEXT("ADFS")
#define VALUE_AUTH_OKTA TEXT("OKTA")

/* Common Auth Settings */
#define KEY_REGION TEXT("REGION")
#define KEY_TOKEN_EXPIRATION TEXT("TOKEN_EXPIRATION")
#define KEY_EXTRA_URL_ENCODE TEXT("EXTRA_URL_ENCODE")

/* IAM */
#define KEY_IAM_HOST TEXT("IAM_HOST")
#define KEY_IAM_PORT TEXT("IAM_PORT")
#define KEY_IAM_IDP_ARN TEXT("IAM_IDP_ARN")
#define KEY_IDP_PORT TEXT("IDP_PORT")
/* Secrets Manager */
#define KEY_SECRET_ID TEXT("SECRET_ID")
#define KEY_SECRET_REGION TEXT("SECRET_REGION")
#define KEY_SECRET_ENDPOINT TEXT("SECRET_ENDPOINT")
/* Federated Auth */
#define KEY_IDP_ENDPOINT TEXT("IDP_ENDPOINT")
#define KEY_IDP_USERNAME TEXT("IDP_USERNAME")
#define KEY_IDP_PASSWORD TEXT("IDP_PASSWORD")
#define KEY_IDP_ROLE_ARN TEXT("IDP_ROLE_ARN")
#define KEY_IDP_SAML_ARN TEXT("IDP_SAML_ARN")
#define KEY_HTTP_SOCKET_TIMEOUT TEXT("HTTP_SOCKET_TIMEOUT")
#define KEY_HTTP_CONNECT_TIMEOUT TEXT("HTTP_CONNECT_TIMEOUT")
/* ADFS */
#define KEY_RELAY_PARTY_ID TEXT("RELAY_PARTY_ID")
/* OKTA */
#define KEY_APP_ID TEXT("APP_ID")

/* Host Selectors */
#define KEY_HOST_SELECTOR_STRATEGY TEXT("HOST_SELECTOR_STRATEGY")
#define VALUE_HIGHEST_WEIGHT_HOST_SELECTOR TEXT("HIGHEST_WEIGHT")
#define VALUE_RANDOM_HOST_SELECTOR TEXT("RANDOM_HOST")
#define VALUE_ROUND_ROBIN_HOST_SELECTOR TEXT("ROUND_ROBIN")

/* Database Dialect */
#define KEY_DATABASE_DIALECT TEXT("DATABASE_DIALECT")
#define VALUE_DB_DIALECT_AURORA_POSTGRESQL TEXT("AURORA_POSTGRESQL")
#define VALUE_DB_DIALECT_AURORA_POSTGRESQL_LIMITLESS TEXT("AURORA_POSTGRESQL_LIMITLESS")

/* Failover */
#define KEY_ENABLE_FAILOVER TEXT("ENABLE_CLUSTER_FAILOVER")
#define KEY_FAILOVER_MODE TEXT("FAILOVER_MODE")
#define VALUE_FAILOVER_MODE_STRICT_READER TEXT("STRICT_READER")
#define VALUE_FAILOVER_MODE_STRICT_WRITER TEXT("STRICT_WRITER")
#define VALUE_FAILOVER_MODE_READER_OR_WRITER TEXT("READER_OR_WRITER")
#define KEY_ENDPOINT_TEMPLATE TEXT("HOST_PATTERN")
#define KEY_IGNORE_TOPOLOGY_REQUEST TEXT("IGNORE_TOPOLOGY_REQUEST_MS")
#define KEY_HIGH_REFRESH_RATE TEXT("TOPOLOGY_HIGH_REFRESH_RATE_MS")
#define KEY_REFRESH_RATE TEXT("TOPOLOGY_REFRESH_RATE_MS")
#define KEY_FAILOVER_TIMEOUT TEXT("FAILOVER_TIMEOUT_MS")
#define KEY_CLUSTER_ID TEXT("CLUSTER_ID")

/* Limitless */
#define KEY_ENABLE_LIMITLESS TEXT("ENABLE_LIMITLESS")
#define KEY_LIMITLESS_MODE TEXT("LIMITLESS_MODE")
#define KEY_LIMITLESS_MONITOR_INTERVAL_MS TEXT("LIMITLESS_MONITOR_INTERVAL_MS")
#define KEY_ROUTER_MAX_RETRIES TEXT("LIMITLESS_ROUTER_MAX_RETRIES")
#define KEY_LIMITLESS_MAX_RETRIES TEXT("LIMITLESS_MAX_RETRIES")
#define VALUE_LIMITLESS_MODE_LAZY TEXT("LAZY")
#define VALUE_LIMITLESS_MODE_IMMEDIATE TEXT("IMMEDIATE")

#endif // CONNECTION_STRING_KEYS_H
