name: Build Underlying Drivers
run-name: Weekly Build - Underlying ODBC Drivers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6am UTC

permissions:
  id-token: write
  contents: read
  actions: write  # Required to delete caches

concurrency:
  group: build-underlying-drivers
  cancel-in-progress: false

jobs:
  build-win-psqlodbc:
    name: Windows - Build psqlODBC
    runs-on: windows-latest
    steps:
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37  # v6
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-drivers-win-psql
      - name: Download psqlODBC
        run: |
          mkdir psqlodbc
          cd psqlodbc
          $DOWNLOAD_URL=$(gh api repos/postgresql-interfaces/psqlodbc/releases --jq '.[0].assets.[] | select(.name=="psqlodbc_x64.msi") | .browser_download_url')
          curl.exe -L ${DOWNLOAD_URL} --output psqlodbc_x64.msi
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Save psqlODBC Cache
        uses: ./.github/actions/s3-cache
        with:
          action: save
          path: psqlodbc
          key: ${{ runner.os }}-psqlodbc-driver
          bucket: ${{ secrets.S3_CACHE_BUCKET }}

  build-macos-psqlodbc:
    name: MacOS - Build psqlODBC
    runs-on:
      - codebuild-odbc-wrapper-macos-pg-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout psqlODBC
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          repository: postgresql-interfaces/psqlodbc
          path: psqlodbc
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          path: wrapper
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37  # v6
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-drivers-mac-psql
      - name: Build psqlodbc
        working-directory: psqlodbc
        run: |
          ./bootstrap
          ./configure
          make
      - name: Save psqlODBC Cache
        uses: ./wrapper/.github/actions/s3-cache
        with:
          action: save
          path: psqlodbc/.libs/
          key: ${{ runner.os }}-psqlodbc-driver
          bucket: ${{ secrets.S3_CACHE_BUCKET }}

  build-linux-psqlodbc:
    name: Linux Ubuntu - Build psqlODBC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout psqlODBC
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          repository: postgresql-interfaces/psqlodbc
          path: psqlodbc
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          path: wrapper
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get install autoconf automake libtool postgresql libpq-dev
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37  # v6
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-drivers-linux-psql
      - name: Download & Build unixODBC
        run: |
          curl -L https://www.unixodbc.org/unixODBC-2.3.12.tar.gz -o unixODBC.tar
          tar xf unixODBC.tar
          cd unixODBC-2.3.12
          ./configure && make
          sudo make install
      - name: Build psqlodbc
        working-directory: psqlodbc
        run: |
          ./bootstrap
          ./configure
          make
      - name: Save psqlODBC Cache
        uses: ./wrapper/.github/actions/s3-cache
        with:
          action: save
          path: psqlodbc/.libs/
          key: ${{ runner.os }}-psqlodbc-driver
          bucket: ${{ secrets.S3_CACHE_BUCKET }}

  build-win-mysql:
    name: Windows - Build MySQL Connector ODBC
    runs-on: windows-latest
    steps:
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37  # v6
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-drivers-win-mysql
      - name: Download mysql-connector
        run: |
          mkdir mysql-connector
          cd mysql-connector
          curl.exe -L "https://dev.mysql.com/get/Downloads/Connector-ODBC/9.5/mysql-connector-odbc-9.5.0-winx64.msi" --output mysql-connector_x64.msi
      - name: Save mysql-connector Cache
        uses: ./.github/actions/s3-cache
        with:
          action: save
          path: mysql-connector
          key: ${{ runner.os }}-mysql-driver
          bucket: ${{ secrets.S3_CACHE_BUCKET }}

  build-macos-mysql:
    name: MacOS - Build MySQL Connector ODBC
    runs-on:
      - codebuild-odbc-wrapper-macos-mysql-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          path: wrapper
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37  # v6
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-drivers-mac-mysql
      - name: Download mysql-connector
        run: |
          mkdir mysql-connector
          curl -L "https://dev.mysql.com/get/Downloads/Connector-ODBC/9.5/mysql-connector-odbc-9.5.0-macos15-arm64.tar.gz" --output mysql-connector_arm64.tar.gz
          tar xvf mysql-connector_arm64.tar.gz --strip-components 1 -C mysql-connector
      - name: Save mysql-connector Cache
        uses: ./wrapper/.github/actions/s3-cache
        with:
          action: save
          path: mysql-connector/
          key: ${{ runner.os }}-mysql-driver
          bucket: ${{ secrets.S3_CACHE_BUCKET }}

  build-linux-mysql:
    name: Linux Ubuntu - Build MySQL Connector ODBC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          path: wrapper
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37  # v6
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-drivers-linux-mysql
      - name: Download mysql-connector
        run: |
          mkdir mysql-connector
          cd mysql-connector
          curl \
            -L "https://dev.mysql.com/get/Downloads/Connector-ODBC/9.5/mysql-connector-odbc_9.5.0-1ubuntu24.04_amd64.deb" \
            --output mysql-connector_x64.deb
      - name: Save mysql-connector Cache
        uses: ./wrapper/.github/actions/s3-cache
        with:
          action: save
          path: mysql-connector/
          key: ${{ runner.os }}-mysql-driver
          bucket: ${{ secrets.S3_CACHE_BUCKET }}
